stages:
  - deploy

deploy_frontend:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh sshpass
  script:
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$DROPLET_IP" 'deploy-frontend.sh'
  only:
    - master